services:
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - "8080:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - "8000:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test  # Este es opcional
volumes:
    persistent:
